### PR TITLE
Tokenize global functions

### LINKED ISSUE #31: Failure to highlight function invocations
This syntax plugin always fails to highlight function invocations on separate lines:

```make
define BUILD_EXE
build_exe_$(1):
	${CARGO} build ${CARGOFLAGS} ${PROFILE_CMD} -p $(1)
endef

EXES := foo bar baz

$(foreach util,$(EXES),$(eval $(call BUILD_EXE,$(util))))
```

Notice the bare invocation at the end. This is an extremely common pattern used to generate rules, and Atom should support it.

### PR DESCRIPTION
**Pull request by 50Wliu**
Fixes #31

@alexchandel can you please try this out and see if it fixes your issue?  Are there any other cases that should be covered?  Any bugs introduced by this PR?  Thanks.

(Also, highlighting really needs to be improved in this package...lines 2 and 3 look so sad in your original example)

### CODE REVIEW

**Comment by alexchandel** [comment]
Sorry, I'm still a noob to Atom package development. How can I test this? I have `atom`/`apm`. If you give me the shell commands I'll just paste them (applying common sense) and run them.

**Comment by 50Wliu** [comment]
`apm develop https://github.com/atom/language-make [optional directory to clone to, default ~/github] && atom --dev` should work.  Alternatively if you don't want to have to use dev mode you can `git clone https://github.com/atom/language-make && cd language-make && apm link && atom`.

**Comment by alexchandel** [comment]
`apm develop https://github.com/atom/language-make` only gives me some `Request for package information failed: Not Found` error, so I had to link it. This successfully highlights global functions.

**Comment by alexchandel** [comment]
@50Wliu Hey just wondering, when will this make it into Atom? It's been a month and my global functions still aren't tokenized... :\

**Comment by 50Wliu** [comment]
I *believe* it should be available starting in Atom 1.9.0.

**Comment by alexchandel** [comment]
O.O good god. Why is the development cycle so glacial? I can understand core features, but this is a bugfix for a bundled package. This should make it into the current beta.

**Pull request merged**
